# Generated by Django 4.1.7 on 2023-03-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_loan_approvaldate_alter_loan_payday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='request',
            new_name='loanRequest',
        ),
    ]
