# Generated by Django 4.1.7 on 2023-03-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_request_loan_loanrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loanRequest',
            new_name='id',
        ),
    ]
