# Generated by Django 4.1.7 on 2023-03-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_payment_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='maximumPayment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='minimumPayment',
            field=models.FloatField(default=10000),
            preserve_default=False,
        ),
    ]
